### ISSUE TITLE
Fix typo: substract => subtract

### ISSUE THREAD

**Issue by ln-north** [adobe/spectrum-css-workflow-icons#2]
### Expected Behavior

- SelectSubstract.svg
- SubstractBackPath.svg
- SubstractFrontSelection.svg

### Actual Behavior

- SelectSubtract.svg
- SubtractBackPath.svg
- SubtractFrontSelection.svg

**Comment by ln-north** [comment]
It's just typo, but renaming will be breaking change for this repo.
I understand it's a little difficult you to answer this issue, so I will wait for your timing.

**Comment by jianliao** [comment]
Hi @ln-north,
Thanks for filing the issue and contributed the PR. I've discussed and confirmed with Adobe Icon designer that instead of removing the wrong name icons, which will cause breaking changes as you pointed out, we are going to add three more icons with correct name.

I currently blocked by an adobe internal package update. I will fix this issue once I got it.

Thanks.
